using System.Globalization;
using System.Text;
using Loom.Api;
using Loom.Models;
using Loom.Models.Nodes;

namespace Loom.Services;

public static class CSharpWorkflowExporter
{
    public static string Export(Workflow workflow, WorkflowSession session)
    {
        var sb = new StringBuilder();

        List<Node> ordered;
        try { ordered = TopologicalSort(workflow); }
        catch { ordered = []; }

        if (ordered.Count == 0) return sb.ToString();

        bool hasApiNodes = ordered.Any(n => n is WeatherNode or GeocodeNode or IpLocationNode or ApiNode);
        bool hasStringReverse = ordered.Any(n => n is StringOpNode { Operation: "Reverse" });

        sb.AppendLine("// Generated by LOOM");
        sb.AppendLine($"// {EscapeComment(workflow.WfName)}");
        sb.AppendLine();
        sb.AppendLine("using System;");
        if (hasStringReverse) sb.AppendLine("using System.Linq;");
        if (hasApiNodes)
        {
            sb.AppendLine("using System.Net.Http;");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine();
            sb.AppendLine("var _http = new HttpClient { Timeout = TimeSpan.FromSeconds(10) };");
        }
        sb.AppendLine();

        var varNames = new Dictionary<Guid, string>();
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var inputIndex = 0;

        foreach (var node in ordered)
        {
            var varName = AssignVarName(node, ref inputIndex, usedNames);
            varNames[node.NodeId] = varName;
            sb.AppendLine(GenerateStep(node, varName, workflow, varNames));
        }

        return sb.ToString();
    }

    private static string AssignVarName(Node node, ref int inputIndex, HashSet<string> used)
    {
        string candidate = node switch
        {
            InputNode => NextLetterName(ref inputIndex),
            ArithmeticNode arith => NameForOp(arith.Operation),
            MultiArithmeticNode multi => NameForOp(multi.Operation),
            LogicNode logic => NameForPredicate(logic.Predicate),
            StringOpNode strOp => NameForStringOp(strOp.Operation),
            StringTransformNode strX => NameForStringTransform(strX.Operation),
            UnaryMathNode unary => NameForUnary(unary.Operation),
            UserDefinedNode => "custom",
            OutputNode output => SanitizeVarName(output.DisplayLabel, "answer"),
            WeatherNode => "weather",
            GeocodeNode => "geocode",
            IpLocationNode => "ipLocation",
            ApiNode => "apiResponse",
            _ => "value"
        };

        return EnsureUnique(candidate, used);
    }

    private static string GenerateStep(
        Node node, string varName, Workflow workflow, Dictionary<Guid, string> varNames)
    {
        string Up(string inputPortName, string emptyDefault = "0")
        {
            var tgtPort = node.InputPorts.FirstOrDefault(p =>
                p.Name.Equals(inputPortName, StringComparison.OrdinalIgnoreCase));
            if (tgtPort is null) return emptyDefault;

            var conn = workflow.Connections.FirstOrDefault(c =>
                c.TargetNodeId == node.NodeId && c.TargetPortId == tgtPort.PortId);
            if (conn is null) return emptyDefault;

            return varNames.TryGetValue(conn.SourceNodeId, out var vn) ? vn : emptyDefault;
        }

        return node switch
        {
            InputNode input =>
                CanvasNodeCatalog.ResolveCanvasType(input)
                    .Equals("StringInput", StringComparison.OrdinalIgnoreCase)
                    ? $"string {varName} = {StringLiteral(input.UserInput?.ToString() ?? "")};"
                    : $"double {varName} = {Literal(input.UserInput)};",

            ArithmeticNode arith =>
                $"double {varName} = {Up("A")} {OpSymbol(arith.Operation)} {Up("B")};",

            MultiArithmeticNode multi =>
                $"double {varName} = {MultiExpression(multi, node, workflow, varNames)};",

            LogicNode logic =>
                $"bool {varName} = {Up("A")} {logic.Predicate} {Up("B")};",

            StringOpNode strOp => strOp.Operation switch
            {
                "ToUpper" => $"var {varName} = {Up("Value", "")}.ToUpperInvariant();",
                "ToLower" => $"var {varName} = {Up("Value", "")}.ToLowerInvariant();",
                "Trim" => $"var {varName} = {Up("Value", "")}.Trim();",
                "Length" => $"var {varName} = {Up("Value", "")}.Length;",
                "Reverse" => $"var {varName} = new string({Up("Value", "")}.Reverse().ToArray());",
                _ => $"var {varName} = {Up("Value", "")};"
            },

            StringTransformNode strX => strX.Operation switch
            {
                "Concat" => $"var {varName} = {Up("A", "")} + {Up("B", "")};",
                "Replace" => $"var {varName} = {Up("A", "")}.Replace({Up("B", "")}, \"\");",
                "Contains" => $"var {varName} = {Up("A", "")}.Contains({Up("B", "")}, StringComparison.OrdinalIgnoreCase);",
                "StartsWith" => $"var {varName} = {Up("A", "")}.StartsWith({Up("B", "")}, StringComparison.OrdinalIgnoreCase);",
                "EndsWith" => $"var {varName} = {Up("A", "")}.EndsWith({Up("B", "")}, StringComparison.OrdinalIgnoreCase);",
                "IndexOf" => $"var {varName} = {Up("A", "")}.IndexOf({Up("B", "")}, StringComparison.OrdinalIgnoreCase);",
                _ => $"var {varName} = {Up("A", "")};"
            },

            UnaryMathNode unary => unary.Operation switch
            {
                "Sqrt" => $"double {varName} = Math.Sqrt({Up("Value")});",
                "Abs" => $"double {varName} = Math.Abs({Up("Value")});",
                "Ceiling" => $"double {varName} = Math.Ceiling({Up("Value")});",
                "Floor" => $"double {varName} = Math.Floor({Up("Value")});",
                "Round" => $"double {varName} = Math.Round({Up("Value")});",
                "Log" => $"double {varName} = Math.Log({Up("Value")});",
                "Log10" => $"double {varName} = Math.Log10({Up("Value")});",
                "Exp" => $"double {varName} = Math.Exp({Up("Value")});",
                "Sin" => $"double {varName} = Math.Sin({Up("Value")});",
                "Cos" => $"double {varName} = Math.Cos({Up("Value")});",
                "Tan" => $"double {varName} = Math.Tan({Up("Value")});",
                "Asin" => $"double {varName} = Math.Asin({Up("Value")});",
                "Acos" => $"double {varName} = Math.Acos({Up("Value")});",
                "Atan" => $"double {varName} = Math.Atan({Up("Value")});",
                "Square" => $"double {varName} = {Up("Value")} * {Up("Value")};",
                "Cube" => $"double {varName} = {Up("Value")} * {Up("Value")} * {Up("Value")};",
                _ => $"double {varName} = {Up("Value")};"
            },

            UserDefinedNode custom => ExportCustomScript(custom, varName, (p, d) => Up(p, d)),

            WeatherNode weather => ExportWeather(weather, varName, (p, d) => Up(p, d)),

            GeocodeNode geocode => ExportGeocode(geocode, varName, (p, d) => Up(p, d)),

            IpLocationNode => $"var {varName} = await _http.GetStringAsync(\"http://ip-api.com/json\");",

            ApiNode api => $"var {varName} = await _http.GetStringAsync({Up("Url")});",

            OutputNode output =>
                output.DisplayFormat == "Json"
                    ? $"var {varName} = {Up("Value")};\nConsole.WriteLine(System.Text.Json.JsonSerializer.Serialize({varName}));"
                    : $"var {varName} = {Up("Value")};\nConsole.WriteLine({varName});",

            _ => $"// {varName} (unsupported node)"
        };
    }

    private static string MultiExpression(
        MultiArithmeticNode multi, Node node, Workflow workflow, Dictionary<Guid, string> varNames)
    {
        var parts = ConnectedInputExprs(node, workflow, varNames);
        if (parts.Count == 0) return "0";

        return multi.Operation switch
        {
            OpType.Add => string.Join(" + ", parts),
            OpType.Multiply => string.Join(" * ", parts),
            OpType.Subtract => parts.Count == 1 ? parts[0] : $"{parts[0]} - ({string.Join(" + ", parts.Skip(1))})",
            OpType.Divide => string.Join(" / ", parts),
            _ => string.Join(" + ", parts)
        };
    }

    private static List<string> ConnectedInputExprs(
        Node node, Workflow workflow, Dictionary<Guid, string> varNames)
    {
        var exprs = new List<string>();
        foreach (var port in node.InputPorts.OrderBy(p => p.Name, StringComparer.OrdinalIgnoreCase))
        {
            if (!port.IsConnected) continue;
            var conn = workflow.Connections.FirstOrDefault(c =>
                c.TargetNodeId == node.NodeId && c.TargetPortId == port.PortId);
            if (conn is null) continue;
            if (varNames.TryGetValue(conn.SourceNodeId, out var vn))
                exprs.Add(vn);
        }
        return exprs;
    }

    private static string ExportCustomScript(UserDefinedNode custom, string varName, Func<string, string, string> up)
    {
        if (TryInlineScriptReturn(custom.ScriptCode, up, out var expr))
            return $"var {varName} = {expr};";

        var lines = new StringBuilder();
        foreach (var line in custom.ScriptCode.Split('\n'))
            lines.AppendLine($"// {line.TrimEnd('\r')}");
        lines.Append($"var {varName} = {up("A", "0")};");
        return lines.ToString();
    }

    private static bool TryInlineScriptReturn(string script, Func<string, string, string> up, out string expr)
    {
        expr = string.Empty;
        if (string.IsNullOrWhiteSpace(script)) return false;

        var trimmed = script.Trim();
        if (!trimmed.StartsWith("return", StringComparison.OrdinalIgnoreCase))
            return false;

        var body = trimmed[6..].Trim().TrimEnd(';');

        body = body
            .Replace("inputs[\"A\"]", up("A", "0"), StringComparison.Ordinal)
            .Replace("inputs[\"a\"]", up("A", "0"), StringComparison.Ordinal)
            .Replace("inputs[\"B\"]", up("B", "0"), StringComparison.Ordinal)
            .Replace("inputs[\"b\"]", up("B", "0"), StringComparison.Ordinal)
            .Replace("(double)", string.Empty, StringComparison.Ordinal);

        expr = body;
        return true;
    }

    private static string ExportWeather(WeatherNode weather, string varName, Func<string, string, string> up)
    {
        var lat = up("Latitude", weather.DefaultLatitude.ToString(CultureInfo.InvariantCulture));
        var lon = up("Longitude", weather.DefaultLongitude.ToString(CultureInfo.InvariantCulture));
        return $"var {varName} = await _http.GetStringAsync($\"https://api.open-meteo.com/v1/forecast?latitude={{{lat}}}&longitude={{{lon}}}&current_weather=true\");";
    }

    private static string ExportGeocode(GeocodeNode geocode, string varName, Func<string, string, string> up)
    {
        var place = up("Place", StringLiteral(geocode.PlaceQuery));
        return $"var {varName} = await _http.GetStringAsync($\"https://nominatim.openstreetmap.org/search?q={{{place}}}&format=json&limit=1\");";
    }

    private static string OpSymbol(OpType op) => op switch
    {
        OpType.Subtract => "-",
        OpType.Multiply => "*",
        OpType.Divide => "/",
        _ => "+"
    };

    private static string NameForOp(OpType op) => op switch
    {
        OpType.Subtract => "diff",
        OpType.Multiply => "product",
        OpType.Divide => "quotient",
        _ => "sum"
    };

    private static string NameForStringOp(string op) => op switch
    {
        "ToUpper" => "upper",
        "ToLower" => "lower",
        "Trim" => "trimmed",
        "Length" => "length",
        "Reverse" => "reversed",
        _ => "text"
    };

    private static string NameForStringTransform(string op) => op switch
    {
        "Concat" => "concat",
        "Replace" => "replaced",
        "Contains" => "contains",
        "StartsWith" => "startsWith",
        "EndsWith" => "endsWith",
        "IndexOf" => "indexOf",
        _ => "transformed"
    };

    private static string NameForUnary(string op) => op switch
    {
        "Sqrt" => "sqrt",
        "Abs" => "abs",
        "Ceiling" => "ceiling",
        "Floor" => "floor",
        "Round" => "rounded",
        "Log" => "log",
        "Log10" => "log10",
        "Exp" => "exp",
        "Sin" => "sin",
        "Cos" => "cos",
        "Tan" => "tan",
        "Asin" => "asin",
        "Acos" => "acos",
        "Atan" => "atan",
        "Square" => "squared",
        "Cube" => "cubed",
        _ => "result"
    };

    private static string NameForPredicate(string predicate) => predicate switch
    {
        "==" => "equal",
        "!=" => "notEqual",
        ">" => "greater",
        ">=" => "gte",
        "<" => "less",
        "<=" => "lte",
        _ => "compare"
    };

    private static string NextLetterName(ref int index)
    {
        const string alphabet = "abcdefghijklmnopqrstuvwxyz";
        var letter = alphabet[index % alphabet.Length];
        index++;
        return index > alphabet.Length ? $"n{letter}" : letter.ToString();
    }

    private static string SanitizeVarName(string? raw, string fallback)
    {
        if (string.IsNullOrWhiteSpace(raw)) return fallback;
        var chars = raw.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray();
        if (chars.Length == 0) return fallback;
        var name = new string(chars);
        if (char.IsDigit(name[0])) name = "v" + name;
        return char.ToLowerInvariant(name[0]) + name[1..];
    }

    private static string EnsureUnique(string baseName, HashSet<string> used)
    {
        var name = baseName;
        var i = 2;
        while (!used.Add(name))
            name = baseName + i++;
        return name;
    }

    private static string Literal(object? value) => value switch
    {
        null => "0",
        double d => d.ToString(CultureInfo.InvariantCulture),
        float f => f.ToString(CultureInfo.InvariantCulture),
        int i => i.ToString(CultureInfo.InvariantCulture),
        _ => double.TryParse(value.ToString(), out var n)
            ? n.ToString(CultureInfo.InvariantCulture)
            : "0"
    };

    private static string StringLiteral(string value) =>
        $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n")}\"";

    private static string EscapeComment(string? text) =>
        (text ?? "").Replace("\r", "").Replace("\n", " ").Replace("*/", "");

    private static List<Node> TopologicalSort(Workflow workflow)
    {
        var inDegree = workflow.Nodes.ToDictionary(n => n.NodeId, _ => 0);
        foreach (var c in workflow.Connections)
            if (inDegree.ContainsKey(c.TargetNodeId))
                inDegree[c.TargetNodeId]++;

        var queue = new Queue<Guid>(inDegree.Where(kv => kv.Value == 0).Select(kv => kv.Key));
        var order = new List<Node>();
        while (queue.Count > 0)
        {
            var id = queue.Dequeue();
            order.Add(workflow.Nodes.First(n => n.NodeId == id));
            foreach (var c in workflow.Connections.Where(c => c.SourceNodeId == id))
            {
                inDegree[c.TargetNodeId]--;
                if (inDegree[c.TargetNodeId] == 0)
                    queue.Enqueue(c.TargetNodeId);
            }
        }

        if (order.Count != workflow.Nodes.Count)
            throw new InvalidOperationException("Cycle detected.");
        return order;
    }
}
